import me from './assets/me1.png';
import icon1 from './assets/icons/coding.png'
import icon2 from './assets/icons/game-development.png'
import icon3 from './assets/icons/web-design.png'
import icon4 from './assets/icons/computer-aided-design.png'
import react from './assets/icons/react-original.svg'
import html from './assets/icons/html5-original.svg'
import css from './assets/icons/css3-original.svg'
import js from './assets/icons/javascript-original.svg'
import flask from './assets/icons/flask-original.svg'
import csharp from './assets/icons/csharp-original.svg'
import cplusplus from './assets/icons/cplusplus-original.svg'
import express from './assets/icons/express-original.svg'
import figma from './assets/icons/figma-original.svg'
import canva from './assets/icons/canva-original.svg'
import unity from './assets/icons/unity-original.svg'
import tailwindcss from './assets/icons/tailwindcss-original.svg'
import python from './assets/icons/python-original.svg'
import photoshop from './assets/icons/photoshop-original.svg'
import illustrator from './assets/icons/illustrator-plain.svg'
import catia from './assets/icons/catia.png'
import solidworks from './assets/icons/solidworks.png'
import autocad from './assets/icons/autocad.png'
import cpcIcon from './assets/icons/brainstorm.png'
import securityIcon from './assets/icons/cyber-security.png'
import roboticsIcon from './assets/icons/rob.png'
import logo from './assets/logo.png'
import ensi from './assets/ensi.png'
import robot from './assets/3jeli.png'
import sniffer from './assets/sniffer.png'
import station from './assets/station.jpg'
import php from './assets/icons/php-original.svg'
import flutter from './assets/icons/flutter.svg'
import arduino from './assets/icons/arduino.svg'
import powershell from './assets/icons/powershell.svg'
import raspberryPiPico from './assets/icons/raspberrypi-pico.svg'
import visualbasic from './assets/icons/visualbasic.svg'




export { php, flutter, arduino, powershell, raspberryPiPico, visualbasic, me, icon1, icon2, icon3, icon4, react, html, css, js, flask, csharp, cplusplus, express, figma, canva, solidworks, catia, autocad, photoshop, illustrator, unity, tailwindcss, python, logo, ensi, robot, sniffer, station, cpcIcon, securityIcon, roboticsIcon};